defaults:
  - dataset: cifar10
  - arch: mobilenet_cifar10_std
  - ensemble: ensemble_params
  - quantization: qunatization_params
  - training: training_params
params:
  data_path: /media/erez/Media/repos/neuralQuantizer/data
